name: Edit-in-comment

on:
  issue_comment:
    types: [created]
jobs:
  pr_commented:
    name: PR comment
    if: ${{ github.event.issue.pull_request && github.event.comment.body== 'Add_checklist_here' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on PR $NUMBER
          echo "$BODY"
          echo $ID
        env:
          NUMBER: ${{ github.event.issue.number }}  
          BODY: ${{ github.event.comment.body }}
          ID: ${{ github.event.comment.id }}
          
      - name: Render template
        id: template
        uses: chuhlomin/render-template@v1.4
        with:
          template: ./.github/comment-template.md
          vars: |
            foo: this
            bar: that
      
      - name: Update Comment
        uses: peter-evans/create-or-update-comment@v2.0.0
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-id: ${{ github.event.comment.id }}
          body: ${{ steps.template.outputs.result }}
          edit-mode: replace
