name: Edit-in-comment

on:
  issue_comment:
    types: [created]
jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request && github.event.comment.body== 'Add_checklist_here' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on PR $NUMBER
          echo "$BODY"
          echo $ID
        env:
          NUMBER: ${{ github.event.issue.number }}  
          BODY: ${{ github.event.comment.body }}
          ID: ${{ github.event.comment.id }}
