name: Edit-in-comment

on:
  issue_comment:
    types: [created]
jobs:
  commentCreated:
    runs-on: ubuntu-latest
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: Add_checklist_here
    
      #- name: Render template
      #  id: template
      #  uses: chuhlomin/render-template@v1.4
      #  with:
      #    template: .github/comment-template.md
      #    vars: |
      #      foo: this
      #      bar: that
            
    # file to read from IS reformat_checklist_template.md
      
      - name: Update comment
        if: steps.fc.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: |
            This comment has been updated!
          edit-mode: replace
          reactions: hooray
